SimchaFund.Web/Models/ErrorViewModel.cs
using SimchaFund.Data;
using System;
using System.Collections.Generic;

namespace SimchaFund.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
    public class SimchosViewModel
    {
        public List<Simcha> Simchos { get; set; }
        public int TotalContributors { get; set; }
    }
    public class ContributorsViewModel
    {
        public List<Contributor> Contributors { get; set; }
    }
    public class HistoryViewModel
    {
        public List<History> Histories { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
    }
    public class ContributionsViewModel
    {
        public List<Contributor> Contributors { get; set; }
        public List<ContribForSimcha> contribForSimcha { get; set; }
        public Simcha Simcha { get; set; }
        public int Counter { get; set; }
    }
}

SimchaFund.Web/Controllers/ContributorsController.cs
using Microsoft.AspNetCore.Mvc;
using SimchaFund.Data;
using SimchaFund.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimchaFund.Web.Controllers
{
    public class ContributorsController : Controller
    {
        private string _connectionString = @"Data Source=.\sqlexpress;Initial Catalog=simchosFund;Integrated Security=true;";
        public IActionResult Index()
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            ContributorsViewModel vm = new ContributorsViewModel
            {
                Contributors = db.GetContributors()
            };
            if (!string.IsNullOrEmpty((string)TempData["message"]))
            {
                ViewBag.Message = (string)TempData["message"];
            }
            return View(vm);
        }
        public IActionResult New(Contributor contributor, decimal initialDeposit)
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            db.NewContributor(contributor, initialDeposit);
            TempData["message"] = "Contributor added successfully";
            return Redirect("/contributors/index");
        }
        public IActionResult Deposit(decimal amount, DateTime date, int contributorId)
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            db.NewDeposit(amount, date, contributorId);
            return Redirect("/contributors/index");
        }
        public IActionResult ShowHistory (int id)
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            List<History> histories = db.GetHistory(id);
            decimal balance = 0;
            histories.ForEach(h => balance += h.Amount);
            List<History> histories1 = histories.OrderByDescending(h => h.Date).ToList();
            HistoryViewModel vm = new HistoryViewModel { Histories = histories1, Name = db.Name(id), Balance = balance};
            return View(vm);
        }
    }
}

SimchaFund.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SimchaFund.Data;
using SimchaFund.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SimchaFund.Web.Controllers
{
    public class SimchosController : Controller
    {
        private string _connectionString = @"Data Source=.\sqlexpress;Initial Catalog=simchosFund;Integrated Security=true;";
        public IActionResult Index()
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            SimchosViewModel vm = new SimchosViewModel
            {
                Simchos = db.GetSimchos(),
                TotalContributors = db.GetContributorTotal()
            };
            if (!string.IsNullOrEmpty((string)TempData["message"]))
            {
                ViewBag.Message = (string)TempData["message"];
            }
            return View(vm);
        }
        [HttpPost]
        public IActionResult New(Simcha simcha)
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            db.AddSimcha(simcha);
            TempData["message"] = "Simcha added successfully";
            return Redirect("/simchos/index");
        }

        public IActionResult Contributions(int simchaId)
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            ContributionsViewModel vm = new ContributionsViewModel
            {
                Contributors = db.GetContributors(),
                Simcha = db.GetSimcha(simchaId),
                Counter = 0,
                contribForSimcha = db.GetIdsForContributed(simchaId)
            };
            return View(vm);
        }
        public IActionResult UpdateContributions(List<History> contributors, int simchaId)
        {
            SimchaFundDb db = new SimchaFundDb(_connectionString);
            List<History> contributors1 = contributors.Where(c => c.Include).ToList();
            db.UpdateContributions(contributors1, simchaId);
            return Redirect("/simchos");
        }
    }
}

SimchaFund.Web/Views/Contributors/Index.cshtml
@using SimchaFund.Data
@model ContributorsViewModel

<div class="container">
    <div class="row col-md-12">
        <div class="col-md-4">
            <button class="btn btn-outline-primary" id="new-contributor">New Contributor</button>
        </div>
        <div class="col-md-4">
            <input type="text" class="form-control" name="search"  id="search" placeholder="Search" value=""/>
        </div>
        <div class="col-md-4">
            <button class="btn btn-outline-danger" id="clear-search">Clear</button>
        </div>
    </div>
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>Deposit</th>
                <th>Name</th>
                <th>Cell</th>
                <th>Balance</th>
                <th>Always include</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Contributor contributor in Model.Contributors)
            {
                <tr>
                    <td><button class="btn btn-outline-info" id="deposit" data-deposit-id="@contributor.Id" data-deposit-name="@contributor.FirstName @contributor.LastName">
                        Deposit</button></td>
                    <td>@contributor.FirstName @contributor.LastName</td>
                    <td>@contributor.Cell</td>
                    <td>@contributor.Balance</td>
                    <td>
                        @if (contributor.AlwaysInclude)
                        {<span style="font-size: 25px;" class="oi oi-check"></span>}
                    </td>
                    <td>
                    <a href="/contributors/showhistory?id=@contributor.Id" class="btn btn-outline-warning">Show history</a>
                        <button class="btn btn-outline-secondary" data-first-name="@contributor.FirstName" data-last-name="@contributor.LastName"
                                data-cell="@contributor.Cell" data-id="@contributor.Id" data-always-include="@contributor.AlwaysInclude" 
                                id="edit-contributor">Edit</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade new-contrib" tabindex="-1" role="dialog" id="contributor-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New Contributor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="/contributors/new">
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>First Name</label>
                            <input class="form-control" id="contributor_first_name" name="firstName" placeholder="First Name" type="text">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Last Name</label>
                            <input class="form-control" id="contributor_last_name" name="lastName" placeholder="Last Name" type="text">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Cell Number</label>
                            <input class="form-control" id="contributor_cell" name="cell" placeholder="Cell Number" type="text">
                        </div>
                        <div class="form-group col-md-6" id="initialDepositDiv">
                            <label>Initial Deposit</label>
                            <input type="text" class="form-control" name="initialDeposit" id="initial_Deposit" placeholder="Initial Deposit">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Created Date</label>
                            <input class="form-control" id="contributor_created_at" name="date" placeholder="Date" type="date">
                        </div>
                        <div>
                            <div class="form-check mt-3 ml-3">
                                <input type="checkbox" class="form-check-input" id="contributor_always_include" name="alwaysInclude" value="true">
                                <label class="form-check-label" for="contributor_always_include">Always Include</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-primary">Save</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<div class="modal fade deposit" tabindex="-1" role="dialog" id="deposit-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deposit for <span id="deposit-name"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="/contributors/deposit">
                <input type="hidden" name="contributorId" id="contributorId"/>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Amount</label>
                        <input class="form-control" name="amount" placeholder="Deposit Amount" type="text">
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        <input type="date" name="date" class="form-control" id="datepicker">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <input class="btn btn-primary" name="commit" type="submit" value="Save">
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

@section scripts {
    <script src="~/js/contributors.js"></script>
}

SimchaFund.Web/Views/Contributors/ShowHistory.cshtml
@model HistoryViewModel
@using SimchaFund.Data

<div class="header">
    <h1>History for @Model.Name</h1>
    <h3>Current Balance: @Model.Balance</h3>
</div>

<div class="row header">
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <tr>
                <th>Action</th>
                <th>Date</th>
                <th>Amount</th>
            </tr>
            @foreach (History history in Model.Histories)
            {
                <tr>
                    <td>
                        @history.Action
                    </td>
                    <td style="text-align: center; vertical-align: middle;">
                        @history.Date.ToLongDateString()
                    </td>
                    <td style="text-align: center; vertical-align: middle;">
                        @history.Amount
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<div style="text-align:center;">
    <a class="btn-lg btn-danger" href="/contributors">Back to Contributors</a>
</div>

SimchaFund.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimchaFund.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimchaFund.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simchos" asp-action="Index">Simchos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contributors" asp-action="Index">Contributors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (!String.IsNullOrEmpty(ViewBag.Message))
        {
            <div class="col-md-12">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    @ViewBag.Message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SimchaFund.Web/Views/Simchos/Contributions.cshtml
@model ContributionsViewModel
@using SimchaFund.Data

<div class="header">
    <h1>
        Contributors for the
        @Model.Simcha.Name
    </h1>
</div>
<div class="table-responsive">
    <form method="POST" action="/simchos/updatecontributions">
        <input type="hidden" name="simchaId" value="@Model.Simcha.Id" />
        <table class="table table-bordered table-striped">
            <tr>
                <th>Contribute</th>
                <th>Name</th>
                <th>Balance</th>
                <th>Always Include</th>
                <th>Amount</th>
            </tr>
            @foreach (Contributor contributor in Model.Contributors)
            {
                <tr>
                    <td>
                        <input type="hidden" name="contributors[@Model.Counter].ContributorId" value="@contributor.Id" />
                            @if (Model.contribForSimcha.Any(c => c.Id == contributor.Id) || contributor.AlwaysInclude)
                            {
                                <input type="checkbox" class="contribute" name="contributors[@Model.Counter].Include" checked value="true"/>
                            }
                            else
                            {
                                <input type="checkbox" class="contribute" name="contributors[@Model.Counter].Include" value="false"/>
                            }
                        
                    </td>
                    <td>@contributor.FirstName @contributor.LastName</td>
                    <td>@contributor.Balance</td>
                    <td style="text-align: center;">
                        @if (contributor.AlwaysInclude)
                        {
                            <span style="font-size: 25px;" class="oi oi-check"></span>
                        }
                    </td>
                    <td>
                        <input type="text" name="contributors[@Model.Counter].amount" class="form-control" value=5 />
                    </td>
                </tr>
                @(Model.Counter++)

            }
        </table>
        <div style="text-align:center;">
            <button class="btn-lg btn-danger">Update</button>
        </div>
    </form>
</div>

@section Scripts {
    <script src="~/js/contributions.js"></script>
}

SimchaFund.Web/Views/Simchos/Index.cshtml
@model SimchosViewModel
@using SimchaFund.Data;

<div class="row col-md-12">
        <div class="col-md-4 offset-4">
            <button class="btn btn-outline-warning" id="new-simcha">New Simcha</button>
        </div>
        <div class="row">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Contributions</th>
                        <th>Simcha Name</th>
                        <th>Contributor Count</th>
                        <th>Total</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Simcha simcha in Model.Simchos)
                    {
                        <tr>
                            <td><a href="/simchos/contributions?simchaid=@simcha.Id" class="btn btn-outline-success">Contributions</a></td>
                            <td>@simcha.Name</td>
                            <td>@simcha.ContributorCount / @Model.TotalContributors</td>
                            <td>@simcha.Total</td>
                            <td>@simcha.Date.ToLongDateString()</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New Simcha</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="/simchos/new" method="post">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="simcha-name">Simcha Name</label>
                            <input type="text" class="form-control" id="simcha-name" name="name" placeholder="Simcha name" />
                        </div>
                        <div class="form-group">
                            <label for="date">Date</label>
                            <input type="date" class="form-control" name="date" id="Date" placeholder="mm/dd/yyyy" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" id="save">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@section Scripts {
    <script src="~/js/index.js"></script>
} 